name: Build
on:
  push:
    branches:
    - release/[0-9]+.[0-9]+
  workflow_dispatch:

concurrency: build

permissions:
  packages: write
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
      ASSEMBLYSEMVER: ${{ steps.version.outputs.ASSEMBLYSEMVER }}

    steps:
      - uses: actions/checkout@v5
        name: Checkout
        with:
          fetch-depth: 0

      - uses: ./.github/actions/versioning/
        id: version
        name: Versioning

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag v${{ steps.version.outputs.VERSION }}
          git push origin v${{ steps.version.outputs.VERSION }}

  build-android:
    runs-on: ubuntu-latest
    needs: versioning

    steps:
      - uses: actions/checkout@v5
        name: Checkout
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build-android/
        name: Build - Android
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.versioning.outputs.VERSION }}
          ASSEMBLYSEMVER: ${{ needs.versioning.outputs.ASSEMBLYSEMVER }}

  github-release:
    runs-on: ubuntu-latest
    needs: [versioning, build-android]

    steps:
      - uses: actions/checkout@v5
        name: Checkout
        with:
          fetch-depth: 0

      - uses: ./.github/actions/create-release/
        name: GitHub Release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.versioning.outputs.VERSION }}
